### ISSUE TITLE
Any way to inject only index.css and skip others?

### ISSUE THREAD

**Issue by Eternal-Rise** [marco-prontera/vite-plugin-css-injected-by-js#113]
My issue about the vite does not include index.css if output entry point is not an html. (https://github.com/vitejs/vite/issues/14192)
As I see, I can fix this with this lib, but I didn't found a way, to include only a specific css files (I want to include only index.css). I don't want to put all my css into js, just index.css, that was skipped by vite after build.

**Comment by marco-prontera** [comment]
Hi, have you tried to import only index.css in your js file?

**Comment by Eternal-Rise** [comment]
I include my main styles file in my root script file. 
![image](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/assets/34982358/1f8c9ca4-08ac-4cb0-94f1-424bce8ad81a)

All other styles defined in components (I am using Vue). By default, all styles are splitted into separate css files. 
When I include this plugin without any options - nothing changes. But with jsAssetsFilterFunction, all css are put to the js :) (I'm not sure, if I can change this somehow) 

![image](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/assets/34982358/d1fdcad8-d44e-48c6-9b1f-537a0f50b77d)

**Comment by Eternal-Rise** [comment]
But I want the opposite :) I want to split my css. So, here is default build output.

![image](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/assets/34982358/d40c5bda-b6ad-4f47-9533-5fc3ef4baf18)

We can see several css files and that is good result. The problem with this, as I mentioned above - main.css are not included. For some reason, it imported only by html via `<link>`, and if the output is .js - it is totally ignored. 

You plugin helps me with that, but another problem appears. There is no more css code splitting. All css are moved to the main.js. The ideal for me, is to include only main.css into main.js, as only this file are missed by vite.
![image](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/assets/34982358/c46bc798-e51e-4a58-8e3f-50b5044be113)


https://github.com/Eternal-Rise/vite-index-css

**Comment by marco-prontera** [comment]
@Eternal-Rise thanks for the explanation, now I understand. Can you try to set as option of my plugin the `relativeCSSInjection` to `true` and see if the result is what you expect? If it does not resolve I will see if I can help you

**Comment by Eternal-Rise** [comment]
It is helps, in some way :) But still not the ideal. Now css are splitted, but still it is injected to js. If I will use `jsAssetsFilterFunction` option with `relativeCSSInjection` - it is looks, like the ideal, but it is vice versa from the original 😄 main.css are injected to main.js, but other css files ignored and not used anywhere

![image](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/assets/34982358/b3a783e6-9a3e-4173-96db-c7613e8a59d4)

**Comment by marco-prontera** [comment]
So you don't want css injection through js but you want only that the main.js uses the main.css right?

**Comment by marco-prontera** [comment]
> It is helps, in some way :) But still not the ideal. Now css are splitted, but still it is injected to js. If I will use `jsAssetsFilterFunction` option with `relativeCSSInjection` - it is looks, like the ideal, but it is vice versa from the original 😄 main.css are injected to main.js, but other css files ignored and not used anywhere
> 
> 
> 
> ![image](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/assets/34982358/b3a783e6-9a3e-4173-96db-c7613e8a59d4)
> 
> 
> 
> 
> 
> UPD: No, my bad. This is exactly what I want :) VSCode ignores search in /dist folder by default, so I don't see usage for the first time
> 
> 

Don't worry, I'm happy it helps you 😉
