### ISSUE TITLE
Improving debugging for relativeCSSInjection 

### ISSUE THREAD

**Issue by grumd** [marco-prontera/vite-plugin-css-injected-by-js#116]
When using `relativeCSSInjection`, `cssCodeSplit` needs to be enabled. This is not documented and unfortunately I didn't know that until I opened the source code of this plugin.

I was using `build.lib` option, so in my configuration `build.cssCodeSplit` was `undefined`, and Vite by default sets it to `false` after resolving configs.

![image](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/assets/5869818/6479e5f0-5228-4ee1-a779-ceb19afddb47)

This plugin only checks `if (config.build.cssCodeSplit == false)` before sending out a warning.

My suggestions:

1. Can `configResolved(_config)` be used for this check? It doesn't have `env.command` but it will have the resolved `false` value for `cssCodeSplit` after Vite decides on the defaults.
2. We could also change the condition to `if (config.build.cssCodeSplit == false || (!config.build.cssCodeSplit && config.build.lib))` but I don't really like that. Vite could change their defaults at any time.
3. Add the information about `cssCodeSplit` to the readme. I'll send a PR for that shortly.

**Comment by marco-prontera** [comment]
Hi, thank you for the issue.
I think it's a good starting point the PR you proposed.
I will merge it asap, thank you for the contribution.
I will valuate others solutions you proposed, but for know I think it's enough
