### ISSUE TITLE
[Bug]: Code from one entry point is injected into all entry points

### ISSUE THREAD

**Issue by WhyNotHugo** [marco-prontera/vite-plugin-css-injected-by-js#118]
# **🐞 Bug Report**

I have multiple entry points, and each of them imports a different css file.

## **Describe the bug**

Styles from one entry point's css file is injected into all other entry points.

### **Is this a regression?**

I believe not.

### **To Reproduce**

I've made a little codebase that reproduces the issue:

```sh
git clone https://git.sr.ht/~whynothugo/vue-multi-page-style-reproducer
cd vue-multi-page-style-reproducer
npm exec -- vite build
```

Upon inspecting `dist/assets/three-39ee0a8d.js` you'll see that it includes the styles from the other entry points -- even though `three.js` includes no styles at all.

### **Expected behaviour**

Each file should only includes styles that it actually imports.

### **Media prove**

n/a

### **Your environment**

* OS: Alpine Linux x86_64
* Node version: v18.18.0
* Npm version: 10.1.0
* Browser name and version: n/a

### **Additional context**

I'm using this plugin to work some complexity around how styles are split into chunks:  https://github.com/vuejs/core/issues/9347

**Comment by WhyNotHugo** [comment]
Note the three entry points defined in `vite.config.js`. They are `one.ts`, `two.ts` and `three.ts`. Only the first two actually import any stylesheets.

**Comment by marco-prontera** [comment]
Hi, thank you for the report.
It sounds like you want to enable the relativeCSSInjection feature, you can find the documentation in the README, let me know if it solve your problem.
Hope it helps let me know
