### ISSUE TITLE
Support for dev server

### ISSUE THREAD

**Issue by bytestream** [marco-prontera/vite-plugin-css-injected-by-js#128]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

I would like to append css to the shadow dom - a feature which is currently unsupported by Vite (https://github.com/vitejs/vite/issues/11855). This plugin currently works great on `vibe build`, but does not run at all on `vite` (development server). My understanding that this is by design - https://github.com/marco-prontera/vite-plugin-css-injected-by-js/blob/main/src/index.ts#L40. 

---

## **Describe the solution you'd like**

* I would like the plugin to run on the `vite` command (development server) as well as `vite build`

---

## **Describe alternatives you've considered**

* I currently have environment specific code which ensures the shadow dom is only used in production. But it is not ideal to have two different code paths.

---

### **Additional context**

*

**Comment by marco-prontera** [comment]
@bytestream Could you give me a sample repository so I can do some testing directly?

**Comment by bytestream** [comment]
@marco-prontera sure, see https://github.com/bytestream/vite-plugin-css-injected-by-js-demo

**Comment by felixpaq** [comment]
Good morning @marco-prontera! Did you have the chance to take a look into this?

**Comment by marco-prontera** [comment]
Hi @felixpaq, I'm working on it ;)

**Comment by marco-prontera** [comment]
@bytestream have you tried?

**Comment by bytestream** [comment]
@marco-prontera it works a treat on my sample repo 👀 the `removeStyleCodeFunction` didn't seem necessary for my use case - the whole page gets refreshed on changes. Thanks very much for your efforts!

**Comment by marco-prontera** [comment]
Available in [v3.4.0](https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/3.4.0), thank you!
