### ISSUE TITLE
[Bug]: Non CSS code is removed from bundled code

### ISSUE THREAD

**Issue by sondreluc** [marco-prontera/vite-plugin-css-injected-by-js#129]
# **🐞 Bug Report**

## **Describe the bug**

* If the bundle code passed to this plugin contains more than one occurrence of `/* empty css */` on the same line (possible when code is minified), it will remove all code between the comments. 

### **To Reproduce**
I experience this in a large code base, after switching from `webpack` with `vite`.
Our minified bundle has, for some unknown reason, more than one occurrence of  `/* empty css */` comments. 
The removal of code between the comments leads the bundled code to be broken.
 
I don't know how to reproduce this exact problem, as I don't know why the `/* empty css */` comments are in the bundled code in the first place. However, you can see the issue at hand in this [Regex repl](https://regex101.com/r/QAsjL1/1), where you can see how the regex in [buildOutputChunkWithCssInjectionCode](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/blob/4048c06146f9c8e478ef2568b0b04f8172d31501/src/utils.ts#L299-L310) will remove more than just the comments.

---

### **Expected behaviour**
`/* empty css */` comments should be removed from the outputted bundle, without removing non related code.

**Comment by marco-prontera** [comment]
Tomorrow, I will make the new release for this fix. Thank you very much.

**Comment by marco-prontera** [comment]
Published the new [version](https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/3.3.1).
Thanks for your contribution!
