### ISSUE TITLE
[Question]: How to use cssAssetsFilterFunction

### ISSUE THREAD

**Issue by ivanzamarro** [marco-prontera/vite-plugin-css-injected-by-js#136]
# **❓ How to use cssAssetsFilterFunction**

Hi @marco-prontera,

First of all, I want to thank you for the excellent work you have done with this plugin. I am seeking a bit of help as I am using it in a project and find myself somewhat stuck with its integration in Vite. It's likely due to some confusion on my part about its use, and I humbly ask if you could shed some light on this matter.

I'm encountering the following problem:

This is my index.html:

```html
<!DOCTYPE html>
<html class="zrc-recom-provider">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body class="zrc-recom-body">
    <div id="creativity-root" class="theme"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
```

Nothing out of the ordinary in this file.

This is the entry point of my application in Vite:

```jsx
// main.jsx

// ...
import './main.css';
import '@company/library/my-library.css';
```

And the following configuration in Vite:

```js
// vite.config.js

// ...

return defineConfig({
    root: __dirname,
    cacheDir: '../../node_modules/.vite/apps/some-app',

    server: {
      port: 4200,
      host: 'localhost',
    },

    preview: {
      port: 4300,
      host: 'localhost',
    },

    plugins: [
      basicSsl(),
      react(),
      cssInjectedByJsPlugin({
          cssAssetsFilterFunction: function customCssAssetsFilterFunction(outputAsset) {
             // i tried several forms !==, includes, etc
              return outputAsset.fileName === '@company/library/my-library.css';
          }
      }),
      nxViteTsPaths(),
    ],
    build: {
      outDir: '../../dist/apps/some-app',
      emptyOutDir: true,
      rollupOptions: {
        output: {
          entryFileNames: `assets/${process.env.VITE_RC_NAMESPACE}.js`,
        },
      },
      reportCompressedSize: true,
      commonjsOptions: {
        transformMixedEsModules: true,
      },
    },
  });
```

I am unable to exclude the stylesheet @company/library/my-library.css to be emitted separately in the final bundle. When printing the outputAsset.fileName to the console, I am getting the already processed content:

```css
{
  fileName: 'assets/index-BCLuweso.css',
  name: 'index.css',
  needsCodeReference: false,
  source: ...
} 
```

Thank you very much for your time and help.

**Comment by marco-prontera** [comment]
Thank you so much!
The cssAssetsFilterFunction operate after the build phase is done, so you can filter the css file in output of the build process from being merged and injected through the final js code in the entry point.
This plugin does not modify the CSS compilation process, this plugin uses the output of the compilation process. to remove the content of some CSS maybe you can solve this problem by using or creating a plugin to replace the content of the imported CSS file using the hook named transform.
if you still need help tell me
