### ISSUE TITLE
[Enhancement]: Allow different output formats, rather than forcing IIFE

### ISSUE THREAD

**Issue by JamShady** [marco-prontera/vite-plugin-css-injected-by-js#137]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

When building my source code, the CSS is injected within an IIFE, which isn't pulled in and integrated with the other IIFE etc being generated. And there's no (configurable) way to stop this.

---

## **Describe the solution you'd like**

Add an option to the plugin config to define the output format, e.g. 'es', and let it default to 'iife' if not defined (or invalid) so existing behaviour is unaffected

**Comment by marco-prontera** [comment]
Hi, thanks for the feedback. can you provide a complete example?

**Comment by JamShady** [comment]
Of? How the setting should be implemented??

So, just allow this:
```
    plugins: [
        cssInjectedByJsPlugin({
            format: 'es',
        }),
    ],
```

And then allow that value to be passed through [here](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/blob/5c6134310ed890a1862bde9f69a7e36ba7c95748/src/utils.ts#L66)

At the moment, in my build output, I'm getting the source like this:

```
(function() { /* CSS code here */ })()
/* originaljavascript output here, which could also be wrapped in an iife or not, depending on what i choose as output format */
```

**Comment by marco-prontera** [comment]
New release with the param you asked for https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/3.5.0, hope it helps you!

**Comment by MuddyPuddlesss** [comment]
if I use `injectionCodeFormat: 'module'`.
After compilation, in the ESM import method, the circled content will not be executed.
<img width="952" alt="image" src="https://github.com/user-attachments/assets/9d6fc1c7-e865-4edc-8955-64a31ddf816b">
