### ISSUE TITLE
[Bug]:  When used together with sentry, sourcemap upload does not work well.

### ISSUE THREAD

**Issue by siosio34** [marco-prontera/vite-plugin-css-injected-by-js#139]
# **🐞 Bug Report**

## **Describe the bug**

When used together with sentry, sourcemap upload does not work well.

If you build Sentry following https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/vite/ without adding this plugin, the sourcemap will be uploaded and the sourcemap file will be mapped well when an error occurs. However, if you add this plugin, error mapping through the .map file will not work properly when an error occurs even if the source map is uploaded.

I think it may be ambiguous to post this here, but Sentry is a monitoring tool used in many products, and I think the library you created is the best for preventing rendering blocking by injecting CSS, so it would be great if these two were compatible together. It's the same.

**Comment by siosio34** [comment]
Does the plugin operate after the build results and sourcemap are created in rollup, making it difficult to map the build results and sourcemap?

**Comment by marco-prontera** [comment]
Sorry for the delay but I was busy.
Exactly the plugin operates after the building process is done. 
It's based on generateBundle hook (https://github.com/marco-prontera/vite-plugin-css-injected-by-js/blob/5c6134310ed890a1862bde9f69a7e36ba7c95748/src/index.ts#L62)

I need some time to figure out how the problem you described can be solved, of course any help is appreciated

**Comment by marco-prontera** [comment]
Hi @siosio34 have you ever tried to set the `topExecutionPriority` param to `false`?

**Comment by siosio34** [comment]
It still doesn't seem to be working well. Looking at the issue, it seems like it's just me. I decided not to write about it for now, so I'll close this issue. Thank you for creating a great library.

**Comment by ramil-musaev** [comment]
Hey guys I face the same issue, @siosio34 did you found a workaround?
