### ISSUE TITLE
[Question]: Is it possible to both output css as well as use this plugin?

### ISSUE THREAD

**Issue by amritk** [marco-prontera/vite-plugin-css-injected-by-js#140]
# **❓ Question or Support Request**

## **Describe your question or ask for support.**

Currently when you add this plugin, the build process no longer outputs a css file. We need the css file for server side rendering. However if someone is only on the client, it would be nice if they did not have to include the css file (as this plugin would inject the code). Is there an option to allow the css file to still get built?

**Comment by amritk** [comment]
Just generate css file as well, as if we did not add the plugin. The linking can be left to the consumer

I might just make two different vite configs actually which should work

**Comment by derekcdaley** [comment]
Is there a setting in the plugin to allow this? Would this work?
 cssInjectedByJsPlugin({
      cssAssetsFilterFunction: function customCssAssetsFilterFunction(outputAsset) {
        return outputAsset.fileName === '*.css';
      }
    }),
