### ISSUE TITLE
[Bug]: Dynamic import of import(" index.css ") is not handled correctly

### ISSUE THREAD

**Issue by 2234839** [marco-prontera/vite-plugin-css-injected-by-js#145]
# **🐞 Bug Report**

## **Describe the bug**

if(false){
import('index.css')
}

In this case, the css will still be imported

---

### **Is this a regression?**

no
---

### **To Reproduce**

<!-- Steps to reproduce the error:
(e.g.:)
code
```js
if(false){
import('index.css')
}
```

---

### **Expected behaviour**

The insertion of css is performed only when import(”index.css“) is run
---

**Comment by marco-prontera** [comment]
Can you provide more info? Have you ever tried also without this plugin?
I'm sure that isn't a problem of this plugin since what it does is taking the output of the Vite building process, this seems strange to me.
