### ISSUE TITLE
[Question]: Title

### ISSUE THREAD

**Issue by DavidVaness** [marco-prontera/vite-plugin-css-injected-by-js#146]
# **❓ Question or Support Request**
Hey Marco, thanks for this plugin. We have been using it for a while now, however I realised that vite also includes this feature now.
So my question is: what is the advantage of using this plugin, over vites ability to automatically handle the css
as written here?
https://vitejs.dev/guide/features.html#css-code-splitting

Possibly also a good addition for the readme 

Thanks David

**Comment by marco-prontera** [comment]
Thanks so much for your question! The feature you refer to does not cover all the functionality and the reason why this plugin was born, can you verify that the output and desired behavior is identical? (In the meantime I close this issue)
