### ISSUE TITLE
[Enhancement]: Allow injector to handle execution before DOMReady

### ISSUE THREAD

**Issue by pixeloution** [marco-prontera/vite-plugin-css-injected-by-js#147]
# Allow injector to handle execution after DOMReady

## **Is your enhancement request related to a problem? Please describe.**
In some cases, the generated code may execute before the DOM is loaded (e.g., built code running as part of an extension) which causes it to fail.

## **Describe the solution you'd like**
You could consider altering the default injector code. Something along the lines of the following would work:

```typescript
function injectCodeFunction(css: string, opts: InjectCodeOptions = {}): void {
    const sheet = new CSSStyleSheet();

    if (document.readyState === 'loading') {
        // DOMContentLoaded can't fire while this code is executing (no race condition)
        document.addEventListener('DOMContentLoaded', () => injectCodeFunction(css, opts))
    }
    else {
        sheet.replace(css).then((stylesheet: CSSStyleSheet) => {
            document.adoptedStyleSheets.push(stylesheet)
        })
    }
}
```

I'm not suggesting you use the `adoptedStylesheets` approach, but I think the `readyState` check would add some robustness to the generated code.

## **Describe alternatives you've considered**
Using the `injectCodeFunction` argument - which is what I'm currently doing.

Nice library, glad I found it, its come in handy.

**Comment by marco-prontera** [comment]
The reason why the plugin has immediate CSS injection as its default code is to have a "similar" behavior to what it would have if it were not used. I think you could introduce a section in the documentation related to these use cases, a kind of Q&A. If you like the idea, feel free to open a PR. Thanks, I'm glad you like it!
