### ISSUE TITLE
Uncaught SyntaxError: Octal escape sequences are not allowed in template strings. (Error with html icons)

### ISSUE THREAD

**Issue by An1984ton** [Marco-Prontera/vite-plugin-css-injected-by-js#16]
Good afternoon)
If css styles have an element ::before
content: '🗸', it is converted to content:"\2714" and an error occurs
Uncaught SyntaxError: Octal escape sequences are not allowed in template strings.

**Comment by Marco-Prontera** [comment]
Hi @An1984ton maybe we need to add a JSON.stringify to the styleCode.
I can fix this problem, give me 2 hours and you will have the new version with the fix.

Thanks for reporting

**Comment by An1984ton** [comment]
> Good afternoon) If css styles have an element ::before content: '🗸', it is converted to content:"\2714" and an error occurs Uncaught SyntaxError: Octal escape sequences are not allowed in template strings.

**Comment by Marco-Prontera** [comment]
@An1984ton the bug is fixed in v1.3.0 😉
