### ISSUE TITLE
Inline css not working. Always empty text node

### ISSUE THREAD

**Issue by awacode21** [Marco-Prontera/vite-plugin-css-injected-by-js#35]
Hello, 

i am building a vue3 component library with vite. I am trying to inline the css so that css is not excluded from bundle file.
Therefore i found your library. I am trying to use it. But whatever i do, the "inlined" code always contain empty text node for the styles. i followed your documentation
I created a very basic stackblitz to showcase. When you run "npm run build" and check dist folder, the inlined code... does not contain the styles:
https://stackblitz.com/edit/inline-css-in-js-not-working?file=vite.config.js,index.js,package.json,style.css&terminal=dev

What i am doing wrong here?

**Comment by Marco-Prontera** [comment]
Hi, let me check and I'll come back with a solution, maybe this plugin does not work well when you configure Vite in `lib` mode.

**Comment by Marco-Prontera** [comment]
@awacode21 Ok, that's a bug. Give me 5 minutes and I will publish a version with the fix

**Comment by awacode21** [comment]
oh my god! me and a colleague are searching for ours what we do wrong!^^ we really appreciate your quick help and hopefully the fix will end our day with a smile.

**Comment by Marco-Prontera** [comment]
@awacode21 https://www.npmjs.com/package/vite-plugin-css-injected-by-js?v=3.14 here the new version [v2.0.2](https://github.com/Marco-Prontera/vite-plugin-css-injected-by-js/releases/tag/v2.0.2)

**Comment by awacode21** [comment]
Thank you so much for the quick fix. I still have a problem. When i try to install the new version it gives me the error that it cannot be found: 
<img width="617" alt="Bildschirmfoto 2022-08-01 um 20 27 59" src="https://user-images.githubusercontent.com/30939926/182218907-651fa037-aa95-46bc-a5a2-20056dd442d1.png">

**Comment by Marco-Prontera** [comment]
@awacode21 Change also the import from `import './style.css?inline`' to `import './style.css'`, since you are in lib mode

**Comment by awacode21** [comment]
> @awacode21 Change also the import from `import './style.css?inline`' to `import './style.css'`, since you are in lib mode

Thanks! already recognized that one. For any reason i cannot install the new version. See comment above.

**Comment by awacode21** [comment]
Ok. Latest problem with import is related to company intern setup stuff, you don't need to care!. Thank you so much for your really fast support. You saved our day!

**Comment by Marco-Prontera** [comment]
@awacode21 Don't worry, thanks for the bug report, and have a nice day!
