### ISSUE TITLE
When styleId is provided as a string it attempts to add the ID but as an undefined variable.

### ISSUE THREAD

**Issue by erikrahm** [Marco-Prontera/vite-plugin-css-injected-by-js#40]
When using the plugin and providing params:

`cssInjectedByJsPlugin({
      topExecutionPriority: false,
      styleId: 'marketplaceStylesheet',
    })`

The ID is added to the created element but not as a string and instead as a variable:

`var t=document.createElement("style");t.id=marketplaceStylesheet`

**Comment by Marco-Prontera** [comment]
Let me check the other issue and I release a new version of this plugin with these fixes
