### ISSUE TITLE
Typescript types for Plugin's parameters make it so that if one argument is provided then both must be provided

### ISSUE THREAD

**Issue by erikrahm** [Marco-Prontera/vite-plugin-css-injected-by-js#41]
The types as defined for the plugins arguments are:

`{
      topExecutionPriority: boolean;
      styleId: string;
    }
  | undefined;`

Which means that you can either provide both arguments or none, there should be the ability to add only one of the arguments.

I'd suggest a simple change like:

`{
      topExecutionPriority?: boolean;
      styleId?: string;
    }
  | undefined;`

**Comment by Marco-Prontera** [comment]
@erikrahm thank you for the contributions here the new version with fixes https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/2.0.4
