### ISSUE TITLE
Issue when using with SSR

### ISSUE THREAD

**Issue by CroModder** [Marco-Prontera/vite-plugin-css-injected-by-js#44]
When using with Next.js or any other framework for Server Side Rendering it will throw the error. It won't fail because it's wrapped with try/catch block (https://github.com/Marco-Prontera/vite-plugin-css-injected-by-js/blob/main/src/utils.ts#L51-L53). But still it would be better to check if this is rendered on the server with:`typeof window !== 'undefined'` so that this is not logged at all.

Output when trying to use lib that is built while using vite-plugin-css-injected-by-js plugin and then rendered on the server:
`vite-plugin-css-injected-by-js ReferenceError: document is not defined`

**Comment by Marco-Prontera** [comment]
Of course, the purpose of this plugin is to create a single file when Vite is used for building a simple JS file and not SSR.
So you suggest not applying the plugin logic when Vite has SSR enabled, right?

Thank you for opening the Issue 😉

**Comment by CroModder** [comment]
Hi Marco, thanks for writing the plugin, it allowed us to use Vite for our lib in the first place :) 
It's a bit different use case because we are using this for bundling a library and not an app, so we don't have control over including this plugin in the consuming apps. Basically we have the same bundle of our lib that's loaded on the client but also on the backend.
I can create PR if you would want to have this in the plugin...

**Comment by Marco-Prontera** [comment]
You are welcome ;) 
Sorry, but I don't understand if your need is to skip plugin logic when SSR is enabled in Vite or not. 
Because checking the 'window' variable is a risky operation, there are other ways to check if the user of that plugin has enabled the SSR option.
I think that this plugin should be skipped when using SSR so I can create the PR to fix this behavior 😜

**Comment by CroModder** [comment]
Not in the Vite bundle itself. Since we are building component library, during the bundling, we don't know if this will be run later on the server or inside browser. (This output/bundle is just a dependency for other consumers)
What do you mean it's a risky operation? By checking for environment I meant something like other maintainers have in their libs (Example of checking for document object before using it: https://github.com/mui/material-ui/issues/18373)
> I think that this plugin should be skipped when using SSR so I can create the PR to fix this behaviour
Yes, this can also improve the plugin, but although closely connected, it will not solve problem specified in this issue.

**Comment by Marco-Prontera** [comment]
> What do you mean it's a risky operation?

Sorry I was thinking of some possible other edge cases (for example if just before a variable "window" is defined) but we can't prevent that.

I'm going to open a PR to add the check suggested and improve also the plugin to skip the execution of itself when SSR is enabled by the user of this plugin.

I will update you when a new version is released

**Comment by CroModder** [comment]
Great!
I made a [commit](https://github.com/Marco-Prontera/vite-plugin-css-injected-by-js/commit/807b67683139d0c5aa73a454b712cedd4bdb9f2e) in by for and wanted to open the PR so you can check it.

**Comment by Marco-Prontera** [comment]
@CroModder Thank you! Open the PR, I will review it.

**Comment by Marco-Prontera** [comment]
@CroModder please try https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/2.1.0-beta-1 and tell me if you see any error in the usage, please

**Comment by CroModder** [comment]
Sure. I'll try it out immediately.

**Comment by CroModder** [comment]
It work like a charm

**Comment by Marco-Prontera** [comment]
Hi, [here](https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/2.1.0) the new version with fixes for SSR, thank you again for the contribution! 😉
