### ISSUE TITLE
Could not find a declaration file with TS 4.7+ and moduleResolution set to Node16

### ISSUE THREAD

**Issue by jroru** [Marco-Prontera/vite-plugin-css-injected-by-js#49]
When i import `cssInjectedByJsPlugin`
```
import cssInjectedByJsPlugin from "vite-plugin-css-injected-by-js";
```

With my `tsconfig.json` as:
```
{
  "compilerOptions": {
    "moduleResolution": "Node16",
  }
}
```
I get:
```
Could not find a declaration file for module 'vite-plugin-css-injected-by-js'. '/package1/node_modules/vite-plugin-css-injected-by-js/dist/esm/index.js' implicitly has an 'any' type.
```

If i add the following line to `vite-plugin-css-injected-by-js/package.json`, the issue resolves:
```
  "exports": {
    ".": {
      + "types": "./dist/esm/declarations/index.d.ts",
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js"
    }
  },
```

This is in-line with [TypeScript's Node 16 ESM suggested package.json](https://www.typescriptlang.org/docs/handbook/esm-node.html#:~:text=%22-,types,-%22%3A%20%22./types/index.d.ts%22%2C).

Awesome package btw. Will submit a PR if this change is supported.

**Comment by Marco-Prontera** [comment]
@jroru Fixed in [v2.1.1](https://github.com/Marco-Prontera/vite-plugin-css-injected-by-js/releases/tag/v2.1.1)
