### ISSUE TITLE
Removing CSS properties not works 

### ISSUE THREAD

**Issue by YaoKaiLun** [marco-prontera/vite-plugin-css-injected-by-js#59]
Remove `font-size` and `cursor` properties:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/11460856/209300423-b3022a5c-8373-492e-a5c7-c96dad3928b9.png">

After Reloading，it generated a new ".en-rte-toolbar-item" style，but the old one didn't remove and it made removing CSS properties not works.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/11460856/209300478-122c0d18-47dd-4bbd-a7f3-4ce86c8a4516.png">

**Comment by marco-prontera** [comment]
Hi, @YaoKaiLun this plugin executes logic only in the build phase. I think your problem is related to other things. If by disabling this plugin the problem disappears please comment on that issue and give me more information about your Vite configuration.
