### ISSUE TITLE
The hashcode for injected style is no correspending

### ISSUE THREAD

**Issue by GuQingPing** [marco-prontera/vite-plugin-css-injected-by-js#60]
The hashcode for injected style is no correspending to component
like this
![image](https://user-images.githubusercontent.com/68961877/211009685-55e29335-9655-48ff-b8ce-2fae898c74f0.png)
![image](https://user-images.githubusercontent.com/68961877/211009765-d3c944fb-b434-4417-8c23-0670868e2853.png)

my config
![image](https://user-images.githubusercontent.com/68961877/211009823-79d63263-37ad-4e8d-b6f0-585048cbfd27.png)

How can i fix it?

**Comment by marco-prontera** [comment]
fixed in [v2.3.0](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/releases/tag/v2.3.0)
