### ISSUE TITLE
Refactor for clarity and ease of extension

### ISSUE THREAD

**Issue by nickhudkins** [marco-prontera/vite-plugin-css-injected-by-js#61]
Firstly, THANK YOU! This plugin has been a life-saver in instances where I am unable to reference additional external assets.

I ran into an issue the other day with strict CSPs preventing `style` tags from being injected without a `nonce`. I have since patched this problem locally but wanted to contribute back.

As I read through the code, I found myself nervous to change code, as the generated code must all be handled as a string e.g. 

```typescript
const defaultInjectCode: InjectCode = (cssCode, { styleId }) =>
    `try{if(typeof document != 'undefined'){var elementStyle = document.createElement('style');${
        typeof styleId == 'string' && styleId.length > 0 ? `elementStyle.id = '${styleId}';` : ''
    }elementStyle.appendChild(document.createTextNode(${cssCode}));document.head.appendChild(elementStyle);}}catch(e){console.error('vite-plugin-css-injected-by-js', e);}`;
```

I believe we can make this simpler for consumers of this plugin to be able to write JavaScript or TypeScript and still generate the code to inject into browsers.

### Proposal:

Currently the injectCode function has the following type:
```typescript 
export type InjectCode = (cssCode: string, options: InjectCodeOptions) => string;
```

If instead we make this type: 
```typescript 
export type InjectCode = (cssCode: string, options: InjectCodeOptions) => void;
```
we can use string interpolation and an `IIFE` format to ease the development of custom injection code, a, la:

```typescript
function injectStyleTag(cssCode: string, options: { styleId?: string }) {
    try {
        if (typeof document != 'undefined') {
            const $style = document.createElement('style');
            if (options.styleId && options.styleId.length > 0) {
               $style.id = options.styleId
            }
            $style.appendChild(document.createTextNode(cssCode));
            document.head.appendChild($style);
        }
    } catch (e) {
        console.error('vite-plugin-css-injected-by-js', e);
    }
}
```
By doing so, we allow consumers to write a function as they would expect to be able to write in-browser, and we can then transform this to:

```typescript
   /* omitted  remainder of plugin for brevity */
   return `(${injectStyleTag})(${cssCode}, ${JSON.stringify({ styleId })})`
```

This works thanks to the fact that calling `.toString()` on a function , returns the entirety of the function definition as a string.

This change will allow for more confident development of injected code, as we would then have the full power of TypeScript type checking, syntax highlighting, and generally less error-prone development since we're not relying on constructing a string other than in a singular place.

**Comment by marco-prontera** [comment]
For the other thing about CSP you can open another issue
