### ISSUE TITLE
Strict CSP disallows injection of `<style>` tags

### ISSUE THREAD

**Issue by nickhudkins** [marco-prontera/vite-plugin-css-injected-by-js#64]
It is possible for the CSS to be injected by the JS generated will be blocked from running with certain configurations of CSPs.

Working from prior-art, `react-jss` supports runtime `nonce` resolution based on a `<meta>` tag:
#### https://cssinjs.org/csp/?v=v10.9.2.

I would like to support a `useStrictCSP` configuration option that adds a nonce to style tags based on `<meta property="csp-nonce" content={{ nonce }} />`

**Comment by marco-prontera** [comment]
released in [v2.3.0](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/releases/tag/v2.3.0)
