### ISSUE TITLE
topExecutionPriority typedef

### ISSUE THREAD

**Issue by alok-runner** [marco-prontera/vite-plugin-css-injected-by-js#67]
`topExecutionPriority` changed from:
`topExecutionPriority?: boolean;`

to:
`topExecutionPriority?: true;`

**Comment by marco-prontera** [comment]
@alok-runner thank you! Here is the new fixed version https://github.com/marco-prontera/vite-plugin-css-injected-by-js/releases/tag/v2.3.1
