### ISSUE TITLE
2.3.1 version missing import style

### ISSUE THREAD

**Issue by tjx666** [marco-prontera/vite-plugin-css-injected-by-js#69]
![image](https://user-images.githubusercontent.com/41773861/212015102-a4754f81-8b6c-4139-9af0-b1106b7320fc.png)

reproduce:

1. git clone git@github.com:tjx666/vite-plugin-css-injected-by-js-issue.git
2. pnpm install
3. pnpm build

versions:

```
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 265.79 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/28086_1673512647873/bin/node
    Pnpm: 7.24.3 
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    @vitejs/plugin-vue2: ^2.2.0 => 2.2.0 
    @vitejs/plugin-vue2-jsx: ^1.1.0 => 1.1.0 
    vite: ^4.0.4 => 4.0.4 
    vite-plugin-css-injected-by-js: ^2.3.1 => 2.3.1 
    vite-plugin-vue-type-imports: ^0.2.4 => 0.2.4 
```

**Comment by marco-prontera** [comment]
Hi @tjx666 Can you explain to me what's your need?

**Comment by marco-prontera** [comment]
@tjx666 I don't know if I understood well, but I think you need to specify in which output file the injection code must be added right?

**Comment by tjx666** [comment]
@marco-prontera 

file `loading.vue` import `loading-icon.vue`.

After build with this plugin:
file loading.mjs import `loading-icon-52ac252a.mjs`, which doesn't contains the css in `loading-icon.vue`. The css of `loading-icon.vue` is in `loading-icon.mjs`.

Another strange problem is why here generate two files: `loading-icon.mjs` and `loading-icon-52ac252a.mjs`

**Comment by marco-prontera** [comment]
@tjx666 Since it's difficult to figure out which js file to add the injectCSS code to, I think I'll implement a configuration parameter to give the possibility to those who have multiple entry-type outputs.
I tried your repository and it's not this plugin's fault that it creates additional files like "`loading-icon-52ac252a.mjs`". This plugin takes the css and adds it into the js via an on-page css injection script.

**Comment by marco-prontera** [comment]
@tjx666 run this `npm i vite-plugin-css-injected-by-js@2.4.0-beta`, follow instructions to use the `jsAssetsFilterFunction` parameter [here](https://github.com/marco-prontera/vite-plugin-css-injected-by-js/blob/feature/%2369/README.md) 

I will make a release in 2 days

**Comment by tjx666** [comment]
1. I think It would be better to support pass a enum value, manualy configure is too complex.
2. Seems this plugin will exact all css to on string? If not, and support split, I think the ideal strategy it to inject the css to the module which import the css first or generate the css.

**Comment by marco-prontera** [comment]
in 2.4.0-beta the warning is already there. The parameter is that function that you can read in the readme. As for the split, I don't know but you could open a PR maybe we can think about it.

Anyway, I'll try the 2.4.0-beta and the parameter will definitely be that function I mentioned before ;) It will be released in two days.

Thanks for the info.
