### ISSUE TITLE
css chunks still generated?

### ISSUE THREAD

**Issue by basbroens** [marco-prontera/vite-plugin-css-injected-by-js#87]
Hi.. love your tool. However.. it still seems to generate css cunks?

![image](https://user-images.githubusercontent.com/24257007/220901055-af0eda02-dc7b-4257-9fca-e3c311f8b0e3.png)

what am i missing? :)

`import { defineConfig } from 'vite'
import path from 'path'
import vue from '@vitejs/plugin-vue'
import cssInjectedByJsPlugin from 'vite-plugin-css-injected-by-js'

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: '@import "@/scss/variables";'
      }
    }
  },
  plugins: [
    vue(),
    cssInjectedByJsPlugin(),
  ],
});
`

**Comment by basbroens** [comment]
btw.. the build isnt generating them, but the are still included in index.js

**Comment by marco-prontera** [comment]
Are still included link references of css inside your index.html? Can you give me more info? This plug-ins by default take all of the css generated and put it as js injection function and also remove all references of css from the index.html. Can you give more informations please so I can help you? It's for you a problem to create a public project that replicate the problem?

**Comment by Kyuoraku** [comment]
Hi, I have the same problem. I just migrated an application to Node 18.15.0 and Vite, and wanted to use your plugin, but I can't figure out what's missing.

**Comment by marco-prontera** [comment]
Hi @Kyuoraku I don't have that problem in my application, can you share a public repository that replicate that problem? Maybe there is something that is causing this issue to you, let me know and if you can share other informations so I can check

**Comment by Kyuoraku** [comment]
Sorry, it was a problem in my project. Already working. Thanks!
