### ISSUE TITLE
manifest json includes non-existing css chunks

### ISSUE THREAD

**Issue by DiFuks** [marco-prontera/vite-plugin-css-injected-by-js#91]
I am using build.manifest=true option

In the generated file, I observe non-existent css files:

```
  "_vendor.19516c05.js": {
    "css": [
      "js/vendor.0b4d51a1.css"
    ],
    "file": "js/vendor.19516c05.js"
  },
```

**Comment by marco-prontera** [comment]
Thank you for reporting! I will check this ASAP

**Comment by marco-prontera** [comment]
Fixed here https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/3.1.1, thank you for reporting let me know if there is something other! ;)

**Comment by DiFuks** [comment]
Cool, works great! Thank you!
