### ISSUE TITLE
When there is no html file the plugin wont work

### ISSUE THREAD

**Issue by gnugomez** [marco-prontera/vite-plugin-css-injected-by-js#95]
right now I'm creating a chrome extension with vite, however due to the app will mount in the host website I do not create any html, instead I create a new element inside the body of the page were I inject the js file, this also inject the styles in the head, but the plugin itself don't work do not even executes.

**Comment by marco-prontera** [comment]
Hi, can you provide me an example and relative steps to reproduce this problem please?

**Comment by gnugomez** [comment]
I will close the issue, the real problem is that I was expecting it to work with HMR and my understanding right now is that the scope of this plugin is only for the build process.
