### ISSUE TITLE
Declarations mismatch when used with Typescript

### ISSUE THREAD

**Issue by susnux** [marco-prontera/vite-plugin-css-injected-by-js#97]
The Typescript compiler complains about a mismatch of the `viteMetadata` declaration, your declaration is missing the `?`:

```
> tsc

node_modules/vite-plugin-css-injected-by-js/dist/esm/declarations/interface.d.ts:7:9 - error TS2687: All declarations of 'viteMetadata' must have identical modifiers.

7         viteMetadata: ChunkMetadata;
          ~~~~~~~~~~~~

node_modules/vite/types/metadata.d.ts:8:5 - error TS2687: All declarations of 'viteMetadata' must have identical modifiers.

8     viteMetadata?: ChunkMetadata
      ~~~~~~~~~~~~


Found 2 errors in 2 files.
```

**Comment by marco-prontera** [comment]
HI! From which version of Vite does this problem occur?
Can you give me an example of how you use this plugin?

**Comment by susnux** [comment]
> From which version of Vite does this problem occur?

Hey, I am using the latest version 4.3.9

>  Can you give me an example of how you use this plugin?

I have a shared config for multiple projects which looks like this:
```ts
import injectCSSPlugin from 'vite-plugin-css-injected-by-js'

export const sharedConfig = () => {
    // ...
    const plugins = []
    if ( /* */) {
        plugins.push(injectCSSPlugin())
    }
    // ...
    return defineConfig({
        // ...
        plugins = [
            ...plugins
        ],
        // ...
    })
}
```

**Comment by marco-prontera** [comment]
Ok I will check if the changes proposed are safe just to be sure

**Comment by marco-prontera** [comment]
@susnux Can you try `npm i vite-plugin-css-injected-by-js@3.1.2-beta.0` , please? Tell me if the problem still occurs please

**Comment by susnux** [comment]
@susnux works for me :)

**Comment by marco-prontera** [comment]
@susnux I'm sorry, I've been very busy. here the new version https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/3.1.2.
Thank you so much for the contribution, everything will be appreciated!
